// Generated by CoffeeScript 1.7.1
(function() {
  var VERBOSE, pkg, utils;

  pkg = require("../package.json");

  VERBOSE = false;

  utils = exports;

  utils.PROGRAM = pkg.name;

  utils.VERSION = pkg.version;

  utils.DESCRIPTION = pkg.description;

  utils.log = function(message) {
    return console.log("" + utils.PROGRAM + ": " + message);
  };

  utils.logError = function(message) {
    utils.log(message);
    return process.exit(1);
  };

  utils.vlog = function(message) {
    if (!VERBOSE) {
      return;
    }
    return utils.log(message);
  };

  utils.verbose = function(value) {
    return VERBOSE = !!value;
  };

  utils.JL = function(object) {
    return JSON.stringify(object, null, 4);
  };

  utils.JS = function(object) {
    return JSON.stringify(object);
  };

}).call(this);
